CREATE TABLE IF NOT EXISTS r_fact_seatgeek_performer_event_relationships (
    event_id INTEGER
    , type VARCHAR
    , name VARCHAR
    , image VARCHAR
    , id INTEGER
    , divisions VARCHAR
    , has_upcoming_events BOOLEAN
    , primary_record VARCHAR
    , image_attribution VARCHAR
    , url VARCHAR
    , score REAL
    , slug VARCHAR
    , home_venue_id VARCHAR
    , short_name VARCHAR
    , num_upcoming_events INTEGER
    , colors VARCHAR
    , image_license VARCHAR
    , popularity INTEGER
    , location VARCHAR
    , image_rights_message VARCHAR
    , images_huge VARCHAR
    , stats_event_count INTEGER
    , event_type VARCHAR
    , event_datetime_utc TIMESTAMP
    , event_datetime_tbd BOOLEAN
    , event_is_open BOOLEAN
    , event_datetime_local TIMESTAMP
    , event_time_tbd BOOLEAN
    , event_short_title VARCHAR
    , event_visible_until_utc TIMESTAMP
    , event_score REAL
    , event_announce_date TIMESTAMP
    , event_created_at TIMESTAMP
    , event_date_tbd BOOLEAN
    , event_title VARCHAR
    , event_popularity REAL
    , event_description VARCHAR
    , event_status VARCHAR
    , event_event_promotion VARCHAR
    , event_conditional BOOLEAN
    , event_enddatetime_utc VARCHAR
    , venue_state VARCHAR
    , venue_name_v2 VARCHAR
    , venue_postal_code VARCHAR
    , venue_name VARCHAR
    , venue_links VARCHAR
    , venue_timezone VARCHAR
    , venue_url VARCHAR
    , venue_score VARCHAR
    , venue_location_lat VARCHAR
    , venue_location_long VARCHAR
    , venue_address VARCHAR
    , venue_country VARCHAR
    , venue_has_upcoming_events VARCHAR
    , venue_num_upcoming_events VARCHAR
    , venue_city VARCHAR
    , venue_slug VARCHAR
    , venue_extended_address VARCHAR
    , venue_id VARCHAR
    , venue_popularity VARCHAR
    , venue_access_method_method VARCHAR
    , venue_access_method_created_at VARCHAR
    , venue_access_method_employee_only VARCHAR
    , venue_metro_code VARCHAR
    , venue_capacity VARCHAR
    , venue_display_location VARCHAR
    , event_stats_listing_count VARCHAR
    , event_stats_average_price VARCHAR
    , event_stats_lowest_price_good_deals VARCHAR
    , event_stats_highest_price VARCHAR
    , event_stats_visible_listing_count VARCHAR
    , event_stats_dq_bucket_counts VARCHAR
    , event_stats_median_price VARCHAR
    , event_stats_lowest_sg_base_price VARCHAR
    , event_stats_lowest_sg_base_price_good_deals VARCHAR
    , event_access_method_method VARCHAR
    , event_access_method_created_at VARCHAR
    , event_access_method_employee_only VARCHAR
    , venue_access_method VARCHAR
    , cycle_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)