INSERT INTO r_fact_seatgeek_performer_event_relationships (
    event_id
    , type
    , name
    , image
    , id
    , divisions
    , has_upcoming_events
    , primary_record
    , image_attribution
    , url
    , score
    , slug
    , home_venue_id
    , short_name
    , num_upcoming_events
    , colors
    , image_license
    , popularity
    , location
    , image_rights_message
    , images_huge
    , stats_event_count
    , event_type
    , event_datetime_utc
    , event_datetime_tbd
    , event_is_open
    , event_datetime_local
    , event_time_tbd
    , event_short_title
    , event_visible_until_utc
    , event_score
    , event_announce_date
    , event_created_at
    , event_date_tbd
    , event_title
    , event_popularity
    , event_description
    , event_status
    , event_event_promotion
    , event_conditional
    , event_enddatetime_utc
    , venue_state
    , venue_name_v2
    , venue_postal_code
    , venue_name
    , venue_links
    , venue_timezone
    , venue_url
    , venue_score
    , venue_location_lat
    , venue_location_long
    , venue_address
    , venue_country
    , venue_has_upcoming_events
    , venue_num_upcoming_events
    , venue_city
    , venue_slug
    , venue_extended_address
    , venue_id
    , venue_popularity
    , venue_access_method_method
    , venue_access_method_created_at
    , venue_access_method_employee_only
    , venue_metro_code
    , venue_capacity
    , venue_display_location
    , event_stats_listing_count
    , event_stats_average_price
    , event_stats_lowest_price_good_deals
    , event_stats_highest_price
    , event_stats_visible_listing_count
    , event_stats_dq_bucket_counts
    , event_stats_median_price
    , event_stats_lowest_sg_base_price
    , event_stats_lowest_sg_base_price_good_deals
    , event_access_method_method
    , event_access_method_created_at
    , event_access_method_employee_only
    , venue_access_method
)

VALUES( 
    %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
    , %s
)